[build]
functions = "netlify/functions"
publish = "dist"
command = "npm run build"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/gateway"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200